//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products
    {
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<decimal> Product_Price { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
    }
}
